import {
  GET_ALL_SESSIONS,
  START_OFFLINE_SESSION,
  END_OFFLINE_SESSION,
  RESEND_SESSION_OTP,
} from "./TrainerTaskService";
export {
  GET_ALL_SESSIONS,
  START_OFFLINE_SESSION,
  END_OFFLINE_SESSION,
  RESEND_SESSION_OTP,
};
