/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{jsx,tsx,ts,js}"],
  theme: {
    extend: {
      gridTemplateColumns: {
        13: "repeat(13, minmax(0, 1fr))",
        14: "repeat(14, minmax(0, 1fr))",
        15: "repeat(15, minmax(0, 1fr))",
        16: "repeat(16, minmax(0, 1fr))",
        17: "repeat(17, minmax(0, 1fr))",
        18: "repeat(18, minmax(0, 1fr))",
        19: "repeat(19, minmax(0, 1fr))",
        20: "repeat(20, minmax(0, 1fr))",
        21: "repeat(21, minmax(0, 1fr))",
        22: "repeat(22, minmax(0, 1fr))",
        23: "repeat(23, minmax(0, 1fr))",
        24: "repeat(24, minmax(0, 1fr))",
        25: "repeat(25, minmax(0, 1fr))",
        26: "repeat(26, minmax(0, 1fr))",
        27: "repeat(27, minmax(0, 1fr))",
        28: "repeat(28, minmax(0, 1fr))",
        29: "repeat(29, minmax(0, 1fr))",
        30: "repeat(30, minmax(0, 1fr))",
      },
      textColor: {
        skin: {
          base: `var(--text-color-primary)`,
          onbgcolor: `var(--bg-color-primary)`,
          err: `var(--color-error)`,
          "on-primary": `var(--on-primary-color)`,
          "on-background": `var(--on-background-color)`,
          error: `var(--error-color)`,
          disabled: `var(--disabled-color)`,
          "btn-primary": `var(--primary-btn-text-color)`,
          "btn-negative": `var(--negative-btn-text-color)`,
          "input-label": `var(--input-label-color)`,
          "input-placeholder": `var(--input-placeholder-color)`,
          "input-value": `var(--input-value-color)`,
          "input-error": `var(--input-error-color)`,
          "form-footer": `var(--form-footer-text-color)`,
          "table-header": `var(--table-header-text-color)`,
          "table-value": `var(--table-value-text-color)`,
          "service-detail": `var(--text-service-details-color)`,
          "error-message": `var(--text-error-user-address-color)`,
          "btn-text": `var(--text-btn-user-address-color)`,
          "radio-gender": `var(--text-radio-gender-color)`,
          gender: `var(--text-gender-color)`,
          grievance: `var(--primary-background-color)`,
          interest: `var(--text-user-interest-color)`,
          "selected-interest": `var(--text-selected-interest-color)`,
          user: `var(--text-user-color)`,
          "user-title": `var(--text-title-color)`,
          "user-hover-group": `var(--text-group-hover-color)`,
          "favorite-label": `var(--text-favorite-color)`,
          "login-label-light": `var(--text--login-color)`,
          trainer: `var(--text--trainer-color)`,
          "event-detail": `var(--text-event-detail-color)`,
          "edit-error": `var(--text-error-edit-profile-color)`,
          "input-edit-profile": `var(--text-input-edit-profile-color)`,
          "label-input-edit-profile": `var(--text-label-edit-profile-color)`,
          "trainer-link": `var(--text-trainer-link)`,
          "trainer-validation": `var(--text-trainer-validation)`,
          "file-upload-btn-cancel": `var(--text-file-upload-btn-cancel)`,
          "post-detail": `var(--text-post-detail-color)`,
          "trainer-availability-schedule-info": `var(--text-trainer-availability-color)`,
          "profile-icon-color": `var(--text-profile-icon-color)`,
          "payment-successful": `var(--text-payment-success-color)`,
          "payment-waiting": `var(--text-payment-waiting-color)`,
          "payment-cancelled": `var(--text-payment-cancelled-color)`,
          "home-text": `var(--text-home-color)`,
          insights: `var(--text-insights-color)`,
          "title-insights": `var(--text-title-insights-color)`,
          "icon-insights": `var(--text-icon-insights-color)`,
          "hover-icon-insights": `var(--text-hover-icon-insights-color)`,
          "dec-insights": `var(--text-dec-insights-color)`,
          "insight-details": `var(--text-insights-details-color)`,
          "tag-insights-details": `var(--text-tag-insights-details-color)`,
        },
      },
      backgroundColor: {
        skin: {
          onbgcolor: `var(--bg-color-primary)`,
          primary: `var(--primary-color)`,
          background: `var(--background-color)`,
          "switch-active": `var(--switch-active-color)`,
          "switch-inactive": `var(--switch-inactive-color)`,
          "switch-cap": `var(--switch-cap-color)`,
          "radio-active": `var(--radio-active-color)`,
          disabled: `var(--disabled-color)`,
          form: `var(--form-color)`,
          "form-footer": `var(--form-footer-color)`,
          "table-base": `var(--table-base-color)`,
          "table-surface": `var(--table-surface-color)`,
          "table-hover": `var(--table-hover-color)`,
          "table-active-page": `var(--table-active-page-color)`,
          "drop-down-floating": `var(--bg-floating-color)`,
          "required-label": `var(--bg-required-label)`,
          "product-service": `var(--bg-product-service-color)`,
          "radio-gender": `var(--bg-radio-gender-color)`,
          "selected-interests": `var(--bg-selected-interest-color)`,
          highlighted: `var(--bg-highlighted-color)`,
          "highlighted-web": `var(--bg-highlighted-web-color)`,
          "folder-details": `var(--bg-folder-details-color)`,
          "event-details": `var(--bg-event-detail-color)`,
          "event-detail-hover": `var(--bg-event-detail-hover-color)`,
          "favorite-image": `var(--bg-image-background-color)`,
          "zoom-meeting-box": `var(--bg-zoom-meeting-box-color)`,
          "zoom-detail-box": `var(--bg-zoom-detail-box-color)`,
          "zoom-detail-header-box": `var(--bg-zoom-detail-header-color)`,
          "home-image": `var(--bg-home-image-color)`,
          profile: `var(--bg-profile-color)`,
          "input-edit-profile": `var(--bg-input-edit-profile-color)`,
          "my-post-draft": `var(--bg-myPosts-draft-color)`,
          "trainer-availability-schedule-info-selected": `var(--bg-trainer-availability-selected-slot)`,
          "trainer-availability-schedule-info-un-selected": `var(--bg-trainer-availability-un-selected-slot)`,
          "background-model": `var(--background-color-model)`,
          "hover-color-list": `var(--services-background-color)`,
          "trainer-availability-schedule-info-selected": `var(--bg-trainer-availability-selected-slot)`,
          "trainer-availability-schedule-info-un-selected": `var(--bg-trainer-availability-un-selected-slot)`,
          "primary-button": `var(--primary-button-color)`,
          "cancel-button": `var(--bg-cancel-button-color)`,
          "home-bg": `var(--bg-home-page-color)`,
          "home-slide": `var(--bg-home-slide-color)`,
          "about-banner": `var(--bg-about-us-color)`,
          insights: `var(--bg-insights-color)`,
          "insights-card": `var(--bg-card-insights-color)`,
          "insights-details": `var(--bg-insights-details-color)`,
          "tag-insights-details": `var(--bg-tag-insights-details-color)`,
          "insights-active-tab": `var(--bg-insights-active-tab-color)`,
          "parallax-section": `var(--bg-parallax-color)`,
          "sign-in-button": `var(--bg-sign-in-button)`,
          "chevron-bg": `var(--bg-offering-chevron)`,
          "on-background": `var(--on-background-color)`,
          "book-slot-button": `var(--bg-offering-booking-button)`,
          "switch-ict": `var(--primary-button-color)`,
          "grey-bg": `var(--grey-bg-color)`,
        },
      },
      borderColor: {
        skin: {
          "input-active": `var(--input-active-border-color)`,
          "input-inactive": `var(--input-inactive-border-color)`,
          "input-error": `var(--input-error-color)`,
          "form-footer": `var(--form-footer-border-color)`,
          table: `var(--table-border-color)`,
          "product-service": `var(--border-service-description-color)`,
          "radio-gender": `var(--border-radio-gender-color)`,
          "selected-interests": `var(--border-selected-interest-color)`,
          "favorite-color": `var(--border-favorite-color)`,
          "zoom-detail-box": `var(--border-detail-color)`,
          "input-edit-profile": `var(--border-input-edit-profile-color)`,
        },
      },
      ringColor: {
        skin: {
          "event-detail": `var(--ring-event-detail-color)`,
          ict: `var(--ring-ict-color)`,
        },
      },
      height: {
        input: "40px",
      },
      width: {
        "bottom-modal": "400px",
      },
      inset: {
        "bottom-modal-position": "39%",
      },
      aspectRatio: {
        "16/9": "16 / 9",
      },
      keyframes: {
        "slide-up": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.5s ease-out forwards",
      },
    },
  },

  plugins: [],
};
