import {
  GET_ALL_PREFERRED_SERVICES,
  DELETE_PREFERRED_SERVICE,
  GET_REMAINING_PREFERRED_SERVICES,
  ADD_PREFERRED_SERVICE,
} from "./TrainerPreferredService";
export {
  GET_ALL_PREFERRED_SERVICES,
  DELETE_PREFERRED_SERVICE,
  ADD_PREFERRED_SERVICE,
  GET_REMAINING_PREFERRED_SERVICES,
};
