import {
  GET_ALL_INSIGHTS,
  GET_ALL_INSIGHTS_BY_ID,
  GET_ALL_INSIGHTS_CATEGORY_PUBLIC,
} from "./InsightsServices";
export {
  GET_ALL_INSIGHTS,
  GET_ALL_INSIGHTS_BY_ID,
  GET_ALL_INSIGHTS_CATEGORY_PUBLIC,
};
