import {
  GET_ALL_PREFERRED_LOCATIONS,
  DELETE_PREFERRED_LOCATION,
  ADD_PREFERRED_LOCATION,
  GET_REMAINING_PREFERRED_LOCATIONS,
  GET_DEFAULT_LOCATION,
} from "./TrainerPreferredLocationService";
export {
  GET_ALL_PREFERRED_LOCATIONS,
  DELETE_PREFERRED_LOCATION,
  ADD_PREFERRED_LOCATION,
  GET_REMAINING_PREFERRED_LOCATIONS,
  GET_DEFAULT_LOCATION,
};
