const data = [
  {
    id: 1,
    project: "React Project 1",
    client: {
      name: "Eshal Rosas",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/1.jpg",
      "https://randomuser.me/api/portraits/women/2.jpg",
      "https://randomuser.me/api/portraits/men/3.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "london",
    number: "+91 123-456-7890",
    country: "UK",
    account: "SBI",
    branch: "Himmatnagar",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 2,
    project: "Angular Project 2",
    client: {
      name: "Sophie Clark",
      avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/4.jpg",
      "https://randomuser.me/api/portraits/men/5.jpg",
      "https://randomuser.me/api/portraits/women/6.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "london",
    number: "+91 123-456-7890",
    country: "UK",
    account: "Mossad",
    branch: "Israel",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 3,
    project: "Vue Project 3",
    client: {
      name: "Caleb Foster",
      avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/7.jpg",
      "https://randomuser.me/api/portraits/women/8.jpg",
      "https://randomuser.me/api/portraits/men/9.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "New York",
    number: "+91 123-456-7890",
    country: "USA",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 4,
    project: "Node.js Project 4",
    client: {
      name: "Ava Doyle",
      avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/11.jpg",
      "https://randomuser.me/api/portraits/women/10.jpg",
      "https://randomuser.me/api/portraits/men/12.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "london",
    number: "+91 123-456-7890",
    country: "UK",
    account: "SBI",
    branch: "Himmatnagar",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 5,
    project: "Django Project 5",
    client: {
      name: "Oscar Hardy",
      avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/14.jpg",
      "https://randomuser.me/api/portraits/men/13.jpg",
      "https://randomuser.me/api/portraits/women/15.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "Surat",
    number: "+91 923-566-2390",
    country: "India",
    account: "SBI",
    branch: "Himmatnagar",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 6,
    project: "Express Project 6",
    client: {
      name: "Lucia Stevens",
      avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/17.jpg",
      "https://randomuser.me/api/portraits/women/16.jpg",
      "https://randomuser.me/api/portraits/men/18.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "New York",
    number: "+91 123-456-7890",
    country: "USA",
    account: "SBI",
    branch: "Himmatnagar",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 7,
    project: "Svelte Project 7",
    client: {
      name: "Darius Wood",
      avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/20.jpg",
      "https://randomuser.me/api/portraits/men/19.jpg",
      "https://randomuser.me/api/portraits/women/21.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "SBI",
    branch: "Himmatnagar",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 8,
    project: "Next.js Project 8",
    client: {
      name: "Emelia Rowe",
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/women/22.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "london",
    number: "+1 123-456-7890",
    country: "UK",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 9,
    project: "Laravel Project 9",
    client: {
      name: "Milo Hubbard",
      avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/26.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
      "https://randomuser.me/api/portraits/women/27.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 10,
    project: "Spring Project 10",
    client: {
      name: "Amara Burns",
      avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/29.jpg",
      "https://randomuser.me/api/portraits/women/28.jpg",
      "https://randomuser.me/api/portraits/men/30.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "london",
    number: "+1 123-456-7890",
    country: "UK",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 11,
    project: "Vue.js Project 11",
    client: {
      name: "Ronin Leonard",
      avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/32.jpg",
      "https://randomuser.me/api/portraits/men/31.jpg",
      "https://randomuser.me/api/portraits/women/33.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 12,
    project: "React  Project 12",
    client: {
      name: "Alara Greer",
      avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/35.jpg",
      "https://randomuser.me/api/portraits/women/34.jpg",
      "https://randomuser.me/api/portraits/men/36.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 13,
    project: "Deno Project 13",
    client: {
      name: "Gloria Robles",
      avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/38.jpg",
      "https://randomuser.me/api/portraits/women/37.jpg",
      "https://randomuser.me/api/portraits/men/39.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "New York",
    number: "+1 123-456-7890",
    country: "USA",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 14,
    project: "Flask Project 14",
    client: {
      name: "Finnian Pennington",
      avatar: "https://randomuser.me/api/portraits/men/40.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/41.jpg",
      "https://randomuser.me/api/portraits/men/40.jpg",
      "https://randomuser.me/api/portraits/women/42.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "london",
    number: "+1 123-456-7890",
    country: "UK",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 15,
    project: "GraphQL Project 15",
    client: {
      name: "Raya Lynn",
      avatar: "https://randomuser.me/api/portraits/women/43.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/44.jpg",
      "https://randomuser.me/api/portraits/women/43.jpg",
      "https://randomuser.me/api/portraits/men/45.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 16,
    project: "Ruby on Rails 16",
    client: {
      name: "Flynn Potter",
      avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/47.jpg",
      "https://randomuser.me/api/portraits/men/46.jpg",
      "https://randomuser.me/api/portraits/women/48.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "New York",
    number: "+1 123-456-7890",
    country: "USA",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 17,
    project: "ASP.NET Project 17",
    client: {
      name: "Rachael Potts",
      avatar: "https://randomuser.me/api/portraits/women/49.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/50.jpg",
      "https://randomuser.me/api/portraits/women/49.jpg",
      "https://randomuser.me/api/portraits/men/51.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 18,
    project: "Go Project 18",
    client: {
      name: "Kyran Foreman",
      avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/women/53.jpg",
      "https://randomuser.me/api/portraits/men/52.jpg",
      "https://randomuser.me/api/portraits/women/54.jpg",
    ],
    payment: "Not Started",
    status: "Active",
    isClicked: false,
    city: "New York",
    number: "+1 123-456-7890",
    country: "USA",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 19,
    project: "TypeScript  19",
    client: {
      name: "Chace Delaney",
      avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/56.jpg",
      "https://randomuser.me/api/portraits/women/55.jpg",
      "https://randomuser.me/api/portraits/men/57.jpg",
    ],
    payment: "Done",
    status: "Active",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  {
    id: 20,
    project: "Dart Project 20",
    client: {
      name: "Kacie Downs",
      avatar: "https://randomuser.me/api/portraits/women/58.jpg",
    },
    users: [
      "https://randomuser.me/api/portraits/men/59.jpg",
      "https://randomuser.me/api/portraits/women/58.jpg",
      "https://randomuser.me/api/portraits/men/60.jpg",
    ],
    payment: "Pending",
    status: "Inactive",
    isClicked: false,
    city: "Surat",
    number: "+1 923-566-2390",
    country: "India",
    account: "RBI",
    branch: "Syria",
    amount: 50000,
    period: "6 months",
  },
  
];

export default data;
