import {
  GET_ALL_SEARCH_HISTORY,
  GET_ALL_SEARCH_RESULT,
  ADD_RECENT_SEARCH_HISTORY,
} from "./SearchService";

export {
  GET_ALL_SEARCH_HISTORY,
  GET_ALL_SEARCH_RESULT,
  ADD_RECENT_SEARCH_HISTORY,
};
