import {
  GET_SERVICE_BY_ID,
  GET_ALL_SERVICE_CATEGORY_FOR_TREND,
  GET_ALL_SERVICE_CATEGORY_FOR_DISCOVER,
  GET_ALL_SERVICE,
  GET_ALL_SERVICE_BY_CATEGORY,
  GET_ALL_SERVICE_BY_CATEGORY_ID,
  RELATED_SERVICE,
  CHECK_FREE_BOOKING,
} from "./ProductServiceTableService";

export {
  GET_SERVICE_BY_ID,
  GET_ALL_SERVICE_CATEGORY_FOR_TREND,
  GET_ALL_SERVICE_CATEGORY_FOR_DISCOVER,
  GET_ALL_SERVICE,
  GET_ALL_SERVICE_BY_CATEGORY,
  GET_ALL_SERVICE_BY_CATEGORY_ID,
  RELATED_SERVICE,
  CHECK_FREE_BOOKING,
};
