import {
  GET_ALL_BLOG_POSTS,
  GET_BLOG_POST_BY_ID,
  CREATE_BLOG_POST,
  DELETE_BLOG_POST,
  UPDATE_BLOG_POST,
  LIKE_BLOG_POST_BY_ID,
  GET_ALL_FEED_POSTS,
  GET_MY_BLOG_POSTS,
} from "./CommunityService";

export {
  GET_ALL_BLOG_POSTS,
  GET_MY_BLOG_POSTS,
  GET_BLOG_POST_BY_ID,
  CREATE_BLOG_POST,
  DELETE_BLOG_POST,
  UPDATE_BLOG_POST,
  LIKE_BLOG_POST_BY_ID,
  GET_ALL_FEED_POSTS,
};
