import {
  GET_TRAINER_BANK_INFO_BY_TRAINER_ID,
  SAVE_TRAINER_BANK_INFO,
  UPDATE_TRAINER_BANK_INFO,
} from "./BankInfoServices";

export {
  GET_TRAINER_BANK_INFO_BY_TRAINER_ID,
  SAVE_TRAINER_BANK_INFO,
  UPDATE_TRAINER_BANK_INFO,
};
