import {
  GET_TRAINER_AVAILABILITY,
  ADD_TRAINER_AVAILABILITY,
  GET_SERVICE_BY_ID_SCHEDULE_INFO,
  GET_TRAINER_AVAILABILITY_BY_ID,
  UPDATE_TRAINER_AVAILABILITY,
  GET_TRAINER_APPROVED_SERVICES,
} from "./TrainerAvailabilityService";

export {
  GET_TRAINER_AVAILABILITY,
  ADD_TRAINER_AVAILABILITY,
  GET_SERVICE_BY_ID_SCHEDULE_INFO,
  GET_TRAINER_AVAILABILITY_BY_ID,
  UPDATE_TRAINER_AVAILABILITY,
  GET_TRAINER_APPROVED_SERVICES,
};
