import {
  MARK_READ_GRIEVANCE,
  GET_GRIEVANCES,
  ADD_GRIEVANCE,
  UPDATE_GRIEVANCE,
  GET_GRIEVANCE_BY_ID,
  ADD_GRIEVANCE_CONVERSATION,
  UPDATE_GRIEVANCE_CONVERSATION,
  GET_GRIEVANCE_BOOKINGS,
} from "./GrievanceService";

export {
  MARK_READ_GRIEVANCE,
  GET_GRIEVANCES,
  ADD_GRIEVANCE,
  UPDATE_GRIEVANCE,
  GET_GRIEVANCE_BY_ID,
  ADD_GRIEVANCE_CONVERSATION,
  UPDATE_GRIEVANCE_CONVERSATION,
  GET_GRIEVANCE_BOOKINGS,
};
